version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-app:local
    ports:
      - "9090:${PORT:-8080}"
    environment:
      PORT: ${PORT:-8080}
      K_SERVICE: my-app
      K_REVISION: 0
      K_CONFIGURATION: my-app
    volumes:
      - .:/app