# docker-compose.access.yml
#https://cloud.google.com/community/tutorials/cloud-run-local-dev-docker-compose
# Usage: 
#   export GCP_KEY_PATH=~/keys/application_default_credentials.json
#   docker-compose -f docker-compose.yml -f docker-compose.access.yml
version: '3'
services:
  app:
    environment:
      # /docs/authentication/production
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/keyfile.json
    volumes:
      # Inject your specific service account keyfile into the container at runtime.
      - ${GCP_KEY_PATH}:/tmp/keys/keyfile.json:ro
